# Generated by Django 4.1.1 on 2022-09-21 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('multicurrency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('answer', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('enable_pixels', models.BooleanField(default=True)),
                ('analytics_base', models.TextField(blank=True, max_length=5000)),
                ('analytics_content_view', models.TextField(blank=True, max_length=5000)),
                ('analytics_lead', models.TextField(blank=True, max_length=5000)),
                ('analytics_purchase', models.TextField(blank=True, max_length=5000)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('product_type', models.CharField(choices=[('subscription', 'subscription'), ('once_only', 'once_only')], default='once_only', max_length=300)),
                ('stripe_price_id', models.CharField(blank=True, max_length=300, null=True)),
                ('days_free_trial', models.IntegerField(blank=True, null=True)),
                ('payment_description', tinymce.models.HTMLField(blank=True, max_length=1000, null=True)),
                ('sales_page_title', models.CharField(max_length=300)),
                ('sales_page_copy_before_media', tinymce.models.HTMLField(blank=True, max_length=10000)),
                ('video_link', models.CharField(blank=True, max_length=300, null=True)),
                ('video_title', tinymce.models.HTMLField(blank=True, max_length=300, null=True)),
                ('whats_included_title', tinymce.models.HTMLField(blank=True, max_length=750)),
                ('sales_page_cta', models.CharField(blank=True, max_length=200, null=True)),
                ('cta_banner', models.CharField(blank=True, max_length=200, null=True)),
                ('content_banner', tinymce.models.HTMLField(blank=True, max_length=5000, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='photos/products')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('num_sold', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('Single Choice', 'Single Choice'), ('Multiple Choice', 'Multiple Choice'), ('Sales Page', 'Sales Page'), ('Text Input', 'Text Input'), ('Image Input', 'Image Input'), ('Email Input', 'Email Input'), ('password', 'password')], max_length=300)),
                ('text_before_title', tinymce.models.HTMLField(blank=True, max_length=10000, null=True)),
                ('question_title', models.CharField(max_length=400)),
                ('question_number', models.IntegerField()),
                ('skippable', models.BooleanField(default=False)),
                ('page_content', tinymce.models.HTMLField(blank=True, max_length=10000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/images')),
                ('input_placeholder', models.CharField(blank=True, max_length=300, null=True)),
                ('image_upload_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_type', models.CharField(choices=[('setUserPreferences', 'setUserPreferences'), ('feedback', 'feedback'), ('updateUserPreferences', 'updateUserPreferences')], default='setUserPreferences', max_length=300)),
                ('name', models.CharField(max_length=300, unique=True)),
                ('display_name', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=400)),
                ('tagline', models.CharField(blank=True, max_length=400, null=True)),
                ('second_tagline', models.CharField(blank=True, max_length=400, null=True)),
                ('unique_id', models.CharField(blank=True, max_length=400, null=True, unique=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('quiz_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('ending_title', models.CharField(blank=True, max_length=400, null=True)),
                ('ending_content', tinymce.models.HTMLField(blank=True, max_length=7000, null=True)),
                ('ending_checkbox', models.BooleanField(default=False)),
                ('ending_checkbox_text', models.CharField(blank=True, max_length=700, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz_backend.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz_backend.product')),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=250, unique=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('latest_fb_clid', models.CharField(blank=True, max_length=500, null=True)),
                ('latest_fbp', models.CharField(blank=True, max_length=500, null=True)),
                ('latest_t_clid', models.CharField(blank=True, max_length=500, null=True)),
                ('ip', models.CharField(blank=True, max_length=2000, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=2000, null=True)),
                ('country_code', models.CharField(blank=True, max_length=250, null=True)),
                ('add_user_agent_to_exclusion_list', models.BooleanField(default=False)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='multicurrency.currency')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_uploads/')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_backend.answer')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('response_id', models.CharField(max_length=500, unique=True)),
                ('steps_completed', models.CharField(blank=True, max_length=500, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('purchased', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=1000, null=True)),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz_backend.quiz')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz_backend.usersession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Referrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.CharField(blank=True, max_length=250, null=True)),
                ('audience', models.CharField(blank=True, max_length=250, null=True)),
                ('ad', models.CharField(blank=True, max_length=250, null=True)),
                ('user_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_backend.usersession')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=200)),
                ('whats_included_text', models.CharField(blank=True, max_length=500, null=True)),
                ('add_to_whats_included', models.BooleanField(default=False)),
                ('prompt_text', models.CharField(blank=True, max_length=500, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_backend.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_backend.quiz'),
        ),
        migrations.AddField(
            model_name='question',
            name='user_preference_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userpreferencetype'),
        ),
        migrations.CreateModel(
            name='ProductPageRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('page_type', models.CharField(choices=[('image_left', 'image_left'), ('image_right', 'image_right'), ('video_left', 'video_left'), ('video_right', 'video_right'), ('story_box', 'story_box')], max_length=1000)),
                ('row_image', models.ImageField(blank=True, null=True, upload_to='photos/products')),
                ('row_video', models.FileField(blank=True, null=True, upload_to='media/products')),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='photos/products')),
                ('media_title', models.CharField(blank=True, max_length=500, null=True)),
                ('cta_text', models.CharField(blank=True, max_length=500, null=True)),
                ('row_text', tinymce.models.HTMLField(blank=True, max_length=5000, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz_backend.product')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz_backend.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question_choice',
            field=models.ManyToManyField(blank=True, to='quiz_backend.questionchoice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_backend.response'),
        ),
    ]
