# Generated by Django 4.1.1 on 2022-09-24 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multicurrency', '0001_initial'),
        ('create_design', '0001_initial'),
        ('emails', '0001_initial'),
        ('quiz_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_subtotal', models.DecimalField(decimal_places=2, max_digits=7)),
                ('order_total', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('one_usd_to_currency_conv_rate_when_placed', models.FloatField(blank=True, default=1, null=True)),
                ('status', models.CharField(choices=[('created', 'created'), ('paid', 'paid'), ('completed', 'completed')], max_length=300)),
                ('order_number', models.CharField(max_length=200, null=True, unique=True)),
                ('order_note', models.CharField(blank=True, max_length=100)),
                ('shipping_method', models.CharField(max_length=200, null=True)),
                ('shipping_price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('ship_first_name', models.CharField(blank=True, max_length=50)),
                ('ship_last_name', models.CharField(blank=True, max_length=50)),
                ('ship_address_line_1', models.CharField(blank=True, max_length=15)),
                ('ship_address_line_2', models.CharField(blank=True, max_length=50)),
                ('ship_country', models.CharField(blank=True, max_length=50)),
                ('ship_state', models.CharField(blank=True, max_length=50)),
                ('ship_city', models.CharField(blank=True, max_length=50)),
                ('ship_postcode', models.CharField(blank=True, max_length=50)),
                ('payment_intent_id', models.CharField(blank=True, max_length=300, null=True)),
                ('order_conf_email_sent', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='multicurrency.currency')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.useremail')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz_backend.usersession')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('design_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='create_design.createdesignrequest')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_design_buy.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='create_design.buyoptions')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_foreignkey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='create_design_buy.shippingoption'),
        ),
    ]
